payment/urls.py
from django.urls import path
from .views import index, charge, payment

app_name = 'payment'

urlpatterns = [
    path('', index, name='home'),
    path('charge/', charge, name='charge'),
    path('payment/', payment, name='payment')
]

stripe_payment/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('payment.urls'))
]

payment/models.py
from django.db import models

# Create your models here.

payment/views.py
from django.shortcuts import render
from stripe_payment.settings import STRIPE_PUBLISHABLE_KEY, STRIPE_SECRET_KEY
import stripe


stripe.api_key = STRIPE_SECRET_KEY

# Create your views here.


def index(request):
    return render(request, 'home.html', {'arr':[5.0,10.0,15.0,20.0]})


def payment(request):
    if request.method == 'POST':
        context = {'key': STRIPE_PUBLISHABLE_KEY, 'amount': request.POST['amount']}
        return render(request, 'payment.html', context)


def charge(request):
    if request.method == 'POST':
        amount = int(float(request.POST['amount']))
        charge = stripe.Charge.create(
            amount=amount,
            currency='usd',
            description='A Django charge',
            source=request.POST['stripeToken']
        )
        return render(request, 'charge.html', {'amount': amount/100})

payment/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  </head>
  <body>
    <div class="container" style="margin-top: 100px;" align="center">
      {% block content%}
      {% endblock %}
    </div>
  </body>
</html>

payment/templates/charge.html
{% extends "base.html" %}
{% block content %}
    <h2>Thanks, you paid <strong>${{amount}}</strong>!</h2>
    <a href="{% url 'payment:home' %}">Home</a>
{% endblock %}

payment/templates/home.html
{% extends "base.html" %}
{% block content %}
    {% for a in arr %}
    <form class="" action="{% url 'payment:payment' %}" method="post">
      <div class="form-group">
        {% csrf_token %}
        <input type="hidden" name="amount" value="{{ a }}">
        <input type="submit" class="btn btn-primary" value="Pay ${{ a }}">
      </div>
    </form>
    {% endfor %}
    <form class="" action="{% url 'payment:payment' %}" method="post">
      <div class="form-group">
        {% csrf_token %}
        <label for="manual">Enter Amount Manually</label>
        <input id="manual" class="form-control" style="width: revert;" type="number" name="amount" value="">
        <p></p>
        <input type="submit" class="btn btn-primary" value="Pay">
      </div>
    </form>
{% endblock %}

payment/templates/payment.html
{% extends "base.html" %}
{% load mathfilters %}
{% block content %}
    <h2>Pay ${{amount}}</h2>
    <form action="{% url 'payment:charge' %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="amount" value="{{ amount|mul:100 }}">
        <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="{{ key }}"
            data-description="A Django Charge"
            data-amount="{{ amount|mul:100 }}"
            data-locale="auto">
        </script>
    </form>
{% endblock %}